### ISSUE TITLE
Errors using Angular CLI

### ISSUE THREAD

**Issue by andelz** [rubenCodeforges/angular2-google-api#9]
While trying to use your Module in a project created using Angular CLI I faced some Errors. They may be caused by something I recognized in earlier projects using the CLI. In some cases CLI is not able to bundle the application code correctly when you are exporting more than one class/interface/component from a single file. In my case I got the following error when trying to run the application (not while packaging/building it):

> Error: No provider for GoogleApiService!

I think the reason is, that you export `GoogleApiService` and `NG_GAPI_CONFIG` from one file.
Could you please verify that your module works with recent CLI projects, because I'd love to use it in my projects?

Thanks a lot!

**Comment by rubenCodeforges** [comment]
Hey thanks for the report. I use the latest cli for development and it's
not about export but about missing provider. I guess I know where the
problem is. I'll check it today

**Comment by rubenCodeforges** [comment]
@andelz tell me one more thing , did you used the npm version or the repo itself ?

**Comment by andelz** [comment]
Used the npm package.

**Comment by rubenCodeforges** [comment]
@andelz  the issue is fixed.
as i told , it was not about exports in one file , this ok and will never be an issue as long as you dont use the `default` flag.

the issue was very easy , ive just forgot to add the GoogleApiService in the module providers field.

Please update ng-gapi to version 0.0.42 ( better remove it first from node_modules then do fresh install)

**Comment by andelz** [comment]
No more errors. Thank you Sir!

**Comment by rubenCodeforges** [comment]
@andelz thank you for your feedback ! I appreciate it !
